version: '3'

# define the network
networks:
  fpm:

services:
  nginx:
    image: mikrowerk/nginx:1.19-alpine
    ports:
      - "80:80"
    networks:
      - fpm
    volumes:
      - type: volume
        source: codeshare
        target: /var/www/html
        volume:
          nocopy: true

  php-fpm:
    image: mikrowerk/php-fpm:7.4
    networks:
      - fpm
    volumes:
      - type: volume
        source: codeshare
        target: /var/www/html
        volume:
          nocopy: true

  codebox:
    image: mikrowerk/codebox:latest
    networks:
      - fpm
    volumes:
      - type: volume
        source: codeshare
        target: /var/www/html

volumes:
  codeshare: