version: '3'
#this version doesn't use shared volumes

# define the network
networks:
  fpm:

services:
  nginx:
    image: mikrowerk/nginx:1.19-alpine:latest
    ports:
      - "80:80"
    networks:
      - fpm

  php-fpm:
    image: mikrowerk/php-fpm:7.4:latest
    networks:
      - fpm
