name: Publish Docker image
on:
  push:
    branches:
    - main
  pull_request:
  
jobs:
  push_to_registry:
    name: Build & Push Docker image to GitHub container registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build and push docker image for php-fpm
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          directory: ./php-fpm
          dockerfile: ./php-fpm/Dockerfile
          image: php-fpm
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GHCR }}
          tags: ${{ github.sha }}
