name: Publish Docker image
on:
  push:
    branches:
    - main
  pull_request:
  
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build and push docker image for php-fpm
        uses: docker/build-push-action@v1
        with:
          context: ./php-fpm
          dockerfile: ./php-fpm/Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GHCR }}
          registry: ghcr.io
          repository: mikrowerk/php-fpm
          tags: ${{ github.sha }}
